### PR TITLE
[doc] use doxygen's comment style

### PR DESCRIPTION
**Pull request by inkydragon**
- comment style: `///`

### CODE REVIEW

**Comment by enterprisey** [comment]
I used this branch to generate doxygen docs and they look great! If I may, can I ask what else needs to be done for this PR to be merged?

**Comment by cody271** [comment]
Hi @enterprisey! Unfortunately doxygen doesn't understand object oriented pure C code very well..

Notice [here](https://libui-ng.github.io/libui-ng/classes.html) at our list of classes that none of the control classes (besides `uiControl` base class) are recognized. Where are `uiButton`, `uiWindow`, and so on?

We have to manually annotate `ui.h` with doxygen [special comments](https://www.doxygen.nl/manual/commands.html) like [this example](https://github.com/jserv/doxygen-oop-in-c/blob/master/manual.c).

**Comment by msink** [comment]
Well, tested briefly annotating as recomended above, works good for me.
Can do a PR with that annotation, easy enough.

```diff
--- a/ui.h
+++ b/ui.h
@@ -74,8 +74,9 @@ _UI_EXTERN void uiOnShouldQuit(int (*f)(void *data), void *data);
 
 _UI_EXTERN void uiFreeText(char *text);
 
-typedef struct uiControl uiControl;
 
+/////////////////////////////////
+/// Base class for all GUI controls (widgets).
 struct uiControl {
 	uint32_t Signature;
 	uint32_t OSSignature;
@@ -92,65 +93,188 @@ struct uiControl {
 	void (*Enable)(uiControl *);
 	void (*Disable)(uiControl *);
 };
-// TOOD add argument names to all arguments
+typedef struct uiControl uiControl;
+// TODO add argument names to all arguments
+
+/// @public @memberof uiControl
 #define uiControl(this) ((uiControl *) (this))
+
+/// Dispose and free all allocated resources.
+/// @public @memberof uiControl
 _UI_EXTERN void uiControlDestroy(uiControl *);
+
+/// Returns the OS-level handle associated with this Control.
+/// @public @memberof uiControl
 _UI_EXTERN uintptr_t uiControlHandle(uiControl *);
+
+/// Returns parent of the control or `NULL` for detached.
+/// @public @memberof uiControl
 _UI_EXTERN uiControl *uiControlParent(uiControl *);
+
+/// Sets parent of the control.
+/// @public @memberof uiControl
 _UI_EXTERN void uiControlSetParent(uiControl *, uiControl *);
+
+/// Returns whether the control is a top level one or not.
+/// @public @memberof uiControl
 _UI_EXTERN int uiControlToplevel(uiControl *);
+
+/// Whether the Control is visible.
+/// @public @memberof uiControl
 _UI_EXTERN int uiControlVisible(uiControl *);
+
+/// Shows the Control.
+/// @public @memberof uiControl
 _UI_EXTERN void uiControlShow(uiControl *);
+
+/// Hides the Control.
+///
+/// Hidden controls do not participate in layout
+/// (that is, Box, GridPane, etc. does not reserve space for hidden controls).
+/// @public @memberof uiControl
 _UI_EXTERN void uiControlHide(uiControl *);
+
+/// Whether the Control is enabled or disabled. Defaults to `true`.
+/// @public @memberof uiControl
 _UI_EXTERN int uiControlEnabled(uiControl *);
+
+/// Enables the Control.
+/// @public @memberof uiControl
 _UI_EXTERN void uiControlEnable(uiControl *);
+
+/// Disables the Control.
+/// @public @memberof uiControl
 _UI_EXTERN void uiControlDisable(uiControl *);
 
+/// @public @memberof uiControl
 _UI_EXTERN uiControl *uiAllocControl(size_t n, uint32_t OSsig, uint32_t typesig, const char *typenamestr);
+
+/// @public @memberof uiControl
 _UI_EXTERN void uiFreeControl(uiControl *);
 
 // TODO make sure all controls have these
+/// @public @memberof uiControl
 _UI_EXTERN void uiControlVerifySetParent(uiControl *, uiControl *);
+/// @public @memberof uiControl
 _UI_EXTERN int uiControlEnabledToUser(uiControl *);
 
 _UI_EXTERN void uiUserBugCannotSetParentOnToplevel(const char *type);
 
+
+/////////////////////////////////
+/// @struct uiWindow
+/// Represents a top-level window.
+///
+/// Contains one child control that occupies the entirety of the window.
+///
+/// @extends uiControl
 typedef struct uiWindow uiWindow;
+
+/// @public @memberof uiWindow
 #define uiWindow(this) ((uiWindow *) (this))
+
+/// @public @memberof uiWindow
 _UI_EXTERN char *uiWindowTitle(uiWindow *w);
+
+/// @public @memberof uiWindow
 _UI_EXTERN void uiWindowSetTitle(uiWindow *w, const char *title);
+
+/// @public @memberof uiWindow
 _UI_EXTERN void uiWindowContentSize(uiWindow *w, int *width, int *height);
+
+/// @public @memberof uiWindow
 _UI_EXTERN void uiWindowSetContentSize(uiWindow *w, int width, int height);
+
+/// @public @memberof uiWindow
 _UI_EXTERN int uiWindowFullscreen(uiWindow *w);
+
+/// @public @memberof uiWindow
 _UI_EXTERN void uiWindowSetFullscreen(uiWindow *w, int fullscreen);
+
+/// @public @memberof uiWindow
 _UI_EXTERN void uiWindowOnContentSizeChanged(uiWindow *w, void (*f)(uiWindow *, void *), void *data);
+
+/// @public @memberof uiWindow
 _UI_EXTERN void uiWindowOnClosing(uiWindow *w, int (*f)(uiWindow *w, void *data), void *data);
+
+/// @public @memberof uiWindow
 _UI_EXTERN int uiWindowBorderless(uiWindow *w);
+
+/// @public @memberof uiWindow
 _UI_EXTERN void uiWindowSetBorderless(uiWindow *w, int borderless);
+
+/// @public @memberof uiWindow
 _UI_EXTERN void uiWindowSetChild(uiWindow *w, uiControl *child);
+
+/// @public @memberof uiWindow
 _UI_EXTERN int uiWindowMargined(uiWindow *w);
+
+/// @public @memberof uiWindow
 _UI_EXTERN void uiWindowSetMargined(uiWindow *w, int margined);
+
+/// @public @memberof uiWindow
 _UI_EXTERN int uiWindowResizeable(uiWindow *w);
+
+/// @public @memberof uiWindow
 _UI_EXTERN void uiWindowSetResizeable(uiWindow *w, int resizeable);
+
+/// @public @memberof uiWindow
 _UI_EXTERN uiWindow *uiNewWindow(const char *title, int width, int height, int hasMenubar);
 
+
+/////////////////////////////////
+/// @struct uiButton
+/// A simple button.
+///
+/// @extends uiControl
 typedef struct uiButton uiButton;
+
+/// @public @memberof uiButton
 #define uiButton(this) ((uiButton *) (this))
+
+/// @public @memberof uiButton
 _UI_EXTERN char *uiButtonText(uiButton *b);
+
+/// @public @memberof uiButton
 _UI_EXTERN void uiButtonSetText(uiButton *b, const char *text);
+
+/// @public @memberof uiButton
 _UI_EXTERN void uiButtonOnClicked(uiButton *b, void (*f)(uiButton *b, void *data), void *data);
+
+/// @public @memberof uiButton
 _UI_EXTERN uiButton *uiNewButton(const char *text);
 
+/// @struct uiBox
+/// a container that stack its children horizontally or vertically.
+///
+/// @extends uiControl
 typedef struct uiBox uiBox;
+
+/// @public @memberof uiBox
 #define uiBox(this) ((uiBox *) (this))
+
+/// @public @memberof uiBox
 _UI_EXTERN void uiBoxAppend(uiBox *b, uiControl *child, int stretchy);
+
+/// @public @memberof uiBox
 _UI_EXTERN int uiBoxNumChildren(uiBox *b);
+
+/// @public @memberof uiBox
 _UI_EXTERN void uiBoxDelete(uiBox *b, int index);
+
+/// @public @memberof uiBox
 _UI_EXTERN int uiBoxPadded(uiBox *b);
+
+/// @public @memberof uiBox
 _UI_EXTERN void uiBoxSetPadded(uiBox *b, int padded);
+
+/// @public @memberof uiBox
 _UI_EXTERN uiBox *uiNewHorizontalBox(void);
+
+/// @public @memberof uiBox
 _UI_EXTERN uiBox *uiNewVerticalBox(void);
 
+
 typedef struct uiCheckbox uiCheckbox;
 #define uiCheckbox(this) ((uiCheckbox *) (this))
 _UI_EXTERN char *uiCheckboxText(uiCheckbox *c);
```

**Comment by msink** [comment]
see #64

**Comment by cody271** [comment]
Duplicate of #96

**Pull request closed without merging**
