### PR TITLE
unix: Fix some of the easy to fix compile time warnings.

### PR DESCRIPTION
**Pull request by szanni**
This is a first step towards removing all compile time warnings, see #84.

This PR addresses easy to fix issues. More work is still needed - those patches might need some discussion/more thorough review though, hence separate PRs.

### CODE REVIEW

**Comment by mohad12211** [comment]
fixing `unix/text.c:16:16 -Wimplicit-function-declaration` also seems easy, we just add `#include <strings.h>` to `unix/uipriv_unix.h` unless i'm missing something

**Comment by szanni** [comment]
> fixing `unix/text.c:16:16 -Wimplicit-function-declaration` also seems easy, we just add `#include <strings.h>` to `unix/uipriv_unix.h` unless i'm missing something Edit: see https://man7.org/linux/man-pages/man3/strcasecmp.3.html#NOTES

That would be the easy fix. The warning highlights a bigger issue for me though: why does `uiprivStricmp` exist in the first place?
IMO further research is needed. Not sure how `strcasecmp` behaves on windows, locale specific stuff, that's my I would put it in a separate PR + discussion. A lot of the `uipriv` functions seem to exist _for the sake of_. In quite a few instances I can not discern why the standard lib functions should not suffice.

**Comment by cody271** [comment]
> That would be the easy fix. The warning highlights a bigger issue for me though: why does `uiprivStricmp` exist in the first place? IMO further research is needed. Not sure how `strcasecmp` behaves on windows, locale specific stuff, that's my I would put it in a separate PR + discussion. A lot of the `uipriv` functions seem to exist _for the sake of_. In quite a few instances I can not discern why the standard lib functions should not suffice.
>
I can provide a bit of the history here: the original purpose of the `uipriv` functions was mainly to help provide consistent behavior on Windows. Particularly for UTF-8 in strings. They were then also useful for being able to add in allocations debugging in a single place in the code.

That being said, these private function wrappers were taken a bit too far in a few places.. like with `uiUnixStrdupText()`. Really the most important thing here, in terms of the API, is just that strings are always freed with `uiFreeText()`.

**Comment by szanni** [comment]
> I can provide a bit of the history here: the original purpose of the `uipriv` functions was mainly to help provide consistent behavior on Windows. Particularly for UTF-8 in strings. They were then also useful for being able to add in allocations debugging in a single place in the code.

While I never understood the allocation wrappers for debugging purposes... debuggers anybody?

It seems like the windows implementation is the only one that may actually work? `strcasecmp` used on darwin and unix will not do what you expect it to when using UTF-8 strings. Unless things have changed we would need a proper unicode library for that.

> That being said, these private function wrappers were taken a bit too far in a few places.. like with `uiUnixStrdupText()`. Really the most important thing here, in terms of the API, is just that strings are always freed with `uiFreeText()`.

The `uiFreeText()` makes a lot of sense, but yeah there seems to be a lot of optimization for _what ifs_. `Premature optimization is the root of all evil` comes to mind for me.
I think we should ensure all strings being returned by `ui` allow for normal string operations, essentially everything apart from `realloc` and `free`.

**Review by cody271 — APPROVED** [review]
LGTM

**Pull request merged**
