### PR TITLE
Clarify string ownership documentation (issue #191)

### PR DESCRIPTION
**Pull request by bcampbell**

### CODE REVIEW

**Review by cody271 — COMMENTED** [review]
Looks good, but I still count 13 lines with "Data is owned by the caller" in `ui.h`:
```shell
libui-ng$ grep caller ui.h | wc -l
13
```

**Comment by bcampbell** [comment]
> Looks good, but I still count 13 lines with "Data is owned by the caller" in `ui.h`:

Those ones are all where data is being returned, and it isn't so ambiguous eg:

`Data is owned by the caller, make sure to call `uiFreeText()`

I think the `uiFreeText()` mention makes it clear enough. The "Data is owned by caller" scans a little oddly, but is technically correct... open to suggestions!

**Comment by cody271** [comment]
> The "Data is owned by caller" scans a little oddly, but is technically correct... open to suggestions!

Yes I think this last part should be changed, since even I was confused by that language from a quick glance at it .. 😛 

Maybe just `Make sure to call uiFreeText().` ?

**Comment by cody271** [comment]
> Those ones are all where data is being returned

Also in these cases maybe the text should be in a `@note`, so that they're harder to miss?

**Comment by szanni** [comment]
For `in` I like the phrasing: `Data is copied internally. Ownership is not transferred.`
I would personally not differentiate between `String` and `Data` and just keep the phrasing consistent for all calls.

For the `out` (return) maybe something like: `Data is copied and ownership is transferred to the caller. Make sure to call uiFreeText().`

The other phrasing I like would be using `clone`:
`Data is cloned internally. Ownership is not transferred.`
`Data is cloned and ownership is transferred to the caller. Make sure to call uiFreeText().`


> > Those ones are all where data is being returned
> 
> Also in these cases maybe the text should be in a `@note`, so that they're harder to miss?


I don't believe moving things to a `@note` is needed or necessarily helpful, as the notes get rendered at the bottom and not where the return is described.  When mixing this with parameters this will get confusing again, as it will be unclear what it refers to exactly. Keeping it in visual proximity is the way to go IMO.
In general this should mainly be regarded as a hint for people that did not read the object lifetimes section of the manual (to be written). We should have a general section describing that: memory in is copied; memory out is copied and you need to free it.
In calls where this is not the case we should probably have a `@warning`.

**Comment by bcampbell** [comment]
OK - new version with some rewording...

**Review by cody271 — APPROVED** [review]
LGTM

**Pull request merged**
