### PR TITLE
update documentation to provide more information about freeing functions

### PR DESCRIPTION
**Pull request by teras**
Functions affected: uiFreeText, uiControlDestroy, uiFreeControl

### CODE REVIEW

**Review by cody271 — COMMENTED** [review]
The header comments need to be in Doxygen format.

**Comment by teras** [comment]
Fixed. Sorry for the error.

**Comment by cody271** [comment]
Instead of copying my off hand comments from the issue into the docs verbatim, try to match the existing voice and style of the doc text a bit more. Keep it concise. For example, no need to prepend `this function is` to any entry.

I would also recommend [building the docs](https://github.com/libui-ng/libui-ng/blob/master/doc/doxygen.md) from source locally to test your PR.

**Comment by teras** [comment]
Updated

**Comment by cody271** [comment]
> Updated

Much better! 👍

**Comment by cody271** [comment]
Only small nit remaining, two trailing whitespace errors in the commit:
```shell
222.patch:24: trailing whitespace.
 * @note Every time a string is returned from the library, this method should be called. 
222.patch:38: trailing whitespace.
 * 
warning: 2 lines add whitespace errors.
```
image

**Comment by cody271** [comment]
Replaced with #227

**Pull request closed without merging**
