### PR TITLE
Fix keyboard shortcuts in uiEntry based controls on macOS

### PR DESCRIPTION
**Pull request by cody271**
See #103

### CODE REVIEW

**Comment by adamierymenko** [comment]
Ooh this is perhaps a better solution, since sometimes you don't want menus.

**Comment by cody271** [comment]
Yes this needs to be fixed first, regardless of any potential future changes to the menu API..

**Comment by cody271** [comment]
Please test this PR without your previous Mac specific patch if possible.

**Comment by cody271** [comment]
Replaced by #107

**Pull request closed without merging**
