### PR TITLE
darwin: Remove uiButton singleton delegate by subclassing.

### PR DESCRIPTION
**Pull request by szanni**
Unclear to me what the whole delegate class story is all about.
Is that an artifact of the memory leak detector? IMO the current state of affairs is horrible.
I compiled and ran things with asan. All good.

### CODE REVIEW

**Comment by szanni** [comment]
Spurious windows build fail.

**Comment by szanni** [comment]
From a purist point of view this mixes view & controller. See my comment in #158

**Comment by cody271** [comment]
> Spurious windows build fail.

I kicked it and CI seems to have passed now.

**Comment by szanni** [comment]
> > Spurious windows build fail.
> 
> I kicked it and CI seems to have passed now.

Spurious build fails happen on my local machine, too, from time to time. Not sure if this is MSVC, ninja or meson.

**Comment by szanni** [comment]
Found a way of triggering a crash without this patch, see my comment in #157

**Comment by szanni** [comment]
Fixed in #176

**Pull request closed without merging**
