### PR TITLE
[Linux] fix drawmatrix transform order to match Windows.

### PR DESCRIPTION
**Pull request by msink**
same as andlabs/libui#383

### CODE REVIEW

**Comment by cody271** [comment]
I don't think any of the "Page 6" tests in`test/drawtests.c` expose this bug?
Does your logo [test](https://github.com/msink/kotlin-libui/blob/master/samples/logo/src/nativeMain/kotlin/main.kt) still expose this bug? Some screenshots of the different behavior would also help.

**Comment by cody271** [comment]
`Direct2D: How to Scale an Object` from tester "Page 6" perhaps? I will try that.

**Comment by cody271** [comment]
Okay just tested with "Page 6" and confirmed: Windows code is correct, other two are wrong.
I will need to port the fix over to macOS next.

See [old issue](https://github.com/andlabs/libui/issues/331)

**Comment by cody271** [comment]
Update: this PR doesn't actually work..

Still wrong behavior on Linux, even with this patch applied:
drawmatrix_unix

Correct on Windows:
drawmatrix_windows

You can see that the smaller rectangle is supposed to be inside the larger one.

MSDN screenshot for reference:
scale-ovw

**Comment by msink** [comment]
Well, it was just cherry-pick from https://github.com/Arisotura/melonDS/commit/dd529f0f5cdf37e4196c1793c3c538be8ebe4cd9
I personall  am completely ignorant in that tranformations, sorry.

Maybe it's jet another bug,

**Comment by cody271** [comment]
Yeah, affine transformations can be a bit tricky.. I've now fixed the bug on Linux and macOS:

drawmatrix_unix_fixed
drawmatrix_darwin_fixed

**Comment by cody271** [comment]
Replaced by #265.

**Pull request closed without merging**
