### PR TITLE
[Old PR libui#508] Add advanced uiTable test suite to page17.

### PR DESCRIPTION
**Pull request by szanni**
I decided to add a more complete uiTable testing suite:

This adds two uiTables backed by the same uiTableModel.
Additionally it provides functions to insert and delete
rows manually.

Issues like the one in #17 [libui#507](https://github.com/andlabs/libui/pull/507)  can be nicely exhibited through the upgraded tester.

### CODE REVIEW

**Comment by inkydragon** [comment]
Play with this pr and #17, sometimes the whole window crashed.

I haven't found a stable crash reproduction method.
You can mix all those steps:
+ Select checkboxes in the top and bottom tables
+ Press "Make yellow" button
+ insert and del row

<details>
<summary>win-x64-debug stacktrace (by windbg)</summary>

```
 # RetAddr               : Args to Child                                                           : Call Site
00 00007ffe`ac835a50     : 00000000`00000000 00000000`00000003 00007ff6`42111698 000000d5`00000004 : ucrtbased!strlen+0x10 [minkernel\crts\ucrt\src\appcrt\string\amd64\strlen.asm @ 58] 
01 00007ff6`42100bed     : abababab`fdfdfdfd 00000000`00000000 00000000`00000050 00007fff`2d5cd936 : libui!uiNewTableValueString+0x20 [D:\proj\Julia\libui-ng\common\tablevalue.c @ 50] 
02 00007ffe`ac83582e     : 00007ff6`42111698 00000260`1929ed00 ffffffff`0000000b 00000000`00000000 : tester!modelCellValue+0x5d [D:\proj\Julia\libui-ng\test\page17.c @ 82] 
03 00007ffe`ac892b5a     : 00000260`1929ed00 000000f5`0000000b 000000f5`00000000 00007fff`2df1369a : libui!uiprivTableModelCellValue+0x3e [D:\proj\Julia\libui-ng\common\tablemodel.c @ 36] 
04 00007ffe`ac89197f     : 000000f5`00000000 000000f5`9f94d230 000000f5`9f94d2b0 00000260`136ee950 : libui!drawTextPart+0x17a [D:\proj\Julia\libui-ng\windows\tabledraw.cpp @ 247] 
05 00007ffe`ac88ae6d     : 00000260`136ec0e0 000000f5`9f94dab8 000000f5`9f94d528 00007ffe`ac86599d : libui!uiprivTableHandleNM_CUSTOMDRAW+0x26f [D:\proj\Julia\libui-ng\windows\tabledraw.cpp @ 657] 
06 00007ffe`ac865740     : 00000260`136ec0e0 00000000`01311a64 000000f5`9f94dab8 000000f5`9f94d528 : libui!onWM_NOTIFY+0xad [D:\proj\Julia\libui-ng\windows\table.cpp @ 248] 
07 00007ffe`ac881531     : 00000000`00000065 000000f5`9f94dab8 000000f5`9f94d528 00000000`00000010 : libui!runWM_NOTIFY+0xa0 [D:\proj\Julia\libui-ng\windows\events.cpp @ 109] 
08 00007ffe`ac89962f     : 00000000`002b2174 000000f5`0000004e 00000000`00000065 000000f5`9f94dab8 : libui!handleParentMessages+0x81 [D:\proj\Julia\libui-ng\windows\parent.cpp @ 127] 
09 00007fff`2defe7e8     : 00000000`002b2174 00007fff`0000004e 00000000`00000065 000000f5`9f94dab8 : libui!utilWindowWndProc+0x5f [D:\proj\Julia\libui-ng\windows\utilwin.cpp @ 23] 
0a 00007fff`2defddab     : 00007ffe`ac8995d0 00007ffe`ac8995d0 00000000`002b2174 00000260`0000004e : USER32!UserCallWinProcCheckWow+0x2f8
0b 00007fff`2defd61a     : 00000000`002b2174 00007fff`40000000 00000000`00000065 00000000`0000004e : USER32!SendMessageWorker+0x70b
0c 00007fff`1be531dd     : 000000f5`9f94dab8 00000260`136ec4d0 00000260`136ec560 00000000`00000000 : USER32!SendMessageW+0xda
0d 00007fff`1be92e79     : 000000f5`9f94da80 000000f5`9f94da80 000000f5`0049414e 00003be8`7539133d : Comctl32!CCSendNotify+0x11d
0e 00007fff`1be4e232     : ffffffff`0000000a ffffffff`0000000a 00000000`0000000b 00000260`151008f0 : Comctl32!CLVDrawItemManager::DrawItem+0x4468d
0f 00007fff`1be55cc5     : 00000000`00000001 00000000`00000000 00000000`00000000 00000260`136ec9b0 : Comctl32!CLVDrawManager::_PaintItems+0x336
10 00007fff`1be55bef     : 00000260`136ec9b0 00000000`7f010c12 00000000`7f010c12 00000260`136ec9b0 : Comctl32!CLVDrawManager::_PaintWorkArea+0xcd
11 00007fff`1be55a23     : 00000260`136ec9b0 00000000`00000000 00000000`00000064 00000260`136ec9b0 : Comctl32!CLVDrawManager::_OnPaintWorkAreas+0x183
12 00007fff`1be5590f     : 00000000`00000000 00000000`00000001 00000260`136ec9b0 0000000d`00000011 : Comctl32!CLVDrawManager::_OnPaint+0xbf
13 00007fff`1be49ba5     : 00000000`00000200 ffffffff`a0100995 00000000`00000000 00000000`00000017 : Comctl32!CLVDrawManager::OnPaint+0x57
14 00007fff`1be490ff     : 00000000`00000001 00000000`0000000f 000000f5`9f94eaa0 00000000`00000000 : Comctl32!CListView::WndProc+0x3d5
15 00007fff`2defe7e8     : cccccccc`cccccccc 00000000`00000001 00000000`00000000 00000000`00000000 : Comctl32!CListView::s_WndProc+0x5f
16 00007fff`2defe47e     : cccccccc`cccccccc 00007fff`1be490a0 00000000`01311a64 cccccccc`0000000f : USER32!UserCallWinProcCheckWow+0x2f8
17 00007fff`1be69aba     : 00000000`00000001 00000000`01311a64 000000f5`9f94e6f0 cccccccc`cccccccc : USER32!CallWindowProcW+0x8e
18 00007fff`1be69799     : 00000000`00000001 00000000`0000000f 00000000`00000000 00000260`136eda50 : Comctl32!CallNextSubclassProc+0x9a
19 00007fff`1be69aba     : cccccccc`cccccccc cccccccc`cccccccc cccccccc`cccccccc cccccccc`cccccccc : Comctl32!TTSubclassProc+0xc9
1a 00007fff`1be699f8     : 00000000`00000001 00000260`136eda50 00000000`01311a64 00000000`00000000 : Comctl32!CallNextSubclassProc+0x9a
1b 00007ffe`ac857548     : 00000000`00000001 000000f5`9f94eaa0 000000f5`9f94e6f0 00000260`21ce06e0 : Comctl32!DefSubclassProc+0x88
1c 00007ffe`ac88ad9c     : 00000000`01311a64 000000f5`0000000f 00000000`00000000 00000000`00000000 : libui!IsolationAwareDefSubclassProc+0xf8 [C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\commctrl.inl @ 3075] 
1d 00007fff`1be69aba     : 00000000`01311a64 00007fff`0000000f 00000000`00000000 00000000`00000000 : libui!tableSubProc+0x44c [D:\proj\Julia\libui-ng\windows\table.cpp @ 189] 
1e 00007fff`1be698b7     : 00000000`00000001 00000000`00000000 00000000`01311a64 00000000`00000000 : Comctl32!CallNextSubclassProc+0x9a
1f 00007fff`2defe7e8     : 00000000`01311a64 00000000`00000001 00000000`00000000 00000000`00000000 : Comctl32!MasterSubclassProc+0xa7
20 00007fff`2defe36c     : 000000f5`9f94e980 00007fff`1be69810 00000000`01311a64 00000000`0000000f : USER32!UserCallWinProcCheckWow+0x2f8
21 00007fff`2df10f93     : 00000000`00000000 00000000`00000000 00000000`00000000 00007fff`1bfbb78d : USER32!DispatchClientMessage+0x9c
22 00007fff`2f770ba4     : 00000000`00000000 00000000`00000001 00000260`136ecd70 00000000`00020000 : USER32!_fnDWORD+0x33
23 00007fff`2cde1464     : 00007fff`1bfb3cd4 00000000`00000000 000000f5`9f94eaa0 00000000`00020000 : ntdll!KiUserCallbackDispatcherContinue
24 00007fff`1bfb3cd4     : 00000000`00000000 000000f5`9f94eaa0 00000000`00020000 00000260`136ecd70 : win32u!NtUserCallHwndLock+0x14
25 00007fff`1be90dd2     : 00000000`00001000 00000000`00000003 00000000`00000001 00007fff`00000001 : Comctl32!CLVScrollingManager::CommonOnScroll+0x290
26 00007fff`1be490ff     : 00000000`00000001 00000000`0000020a 00000000`00000407 00000000`00000000 : Comctl32!CListView::WndProc+0x47602
27 00007fff`2defe7e8     : cccccccc`cccccccc 00000000`00000001 00000000`ff880000 00000000`00000000 : Comctl32!CListView::s_WndProc+0x5f
28 00007fff`2defe47e     : 00000000`00000000 00007fff`1be490a0 00000000`01311a64 cccccccc`0000020a : USER32!UserCallWinProcCheckWow+0x2f8
29 00007fff`1be69aba     : 00000000`00000001 00000000`01311a64 000000f5`9f94f330 00000000`00000000 : USER32!CallWindowProcW+0x8e
2a 00007fff`1be69799     : 00000000`00000001 00000000`0000020a 00000000`00000000 00000260`136eda50 : Comctl32!CallNextSubclassProc+0x9a
2b 00007fff`1be69aba     : cccccccc`cccccccc cccccccc`cccccccc cccccccc`cccccccc cccccccc`cccccccc : Comctl32!TTSubclassProc+0xc9
2c 00007fff`1be699f8     : 00000000`00000001 00000260`136eda50 00000000`01311a64 00000000`00000000 : Comctl32!CallNextSubclassProc+0x9a
2d 00007ffe`ac857548     : 00000000`00000001 00000000`001a226a 000000f5`9f94f330 cccccccc`cccccccc : Comctl32!DefSubclassProc+0x88
2e 00007ffe`ac88ad9c     : 00000000`01311a64 cccccccc`0000020a 00000000`ff880000 00000000`01b203c0 : libui!IsolationAwareDefSubclassProc+0xf8 [C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\commctrl.inl @ 3075] 
2f 00007fff`1be69aba     : 00000000`01311a64 cccccccc`0000020a 00000000`ff880000 00000000`01b203c0 : libui!tableSubProc+0x44c [D:\proj\Julia\libui-ng\windows\table.cpp @ 189] 
30 00007fff`1be698b7     : 00000000`00000001 00000000`ff880000 00000000`01311a64 00000000`01b203c0 : Comctl32!CallNextSubclassProc+0x9a
31 00007fff`2defe7e8     : 000000f5`9f94f548 000000f5`9f94f528 00000000`00000001 00000000`00000000 : Comctl32!MasterSubclassProc+0xa7
32 00007fff`2defe229     : 00000000`00000000 00007fff`1be69810 00000000`01311a64 00000000`0000020a : USER32!UserCallWinProcCheckWow+0x2f8
33 00007fff`2defbfe0     : 00007fff`1be69810 00000260`13da0bc0 000000f5`9f94f688 00000000`00000000 : USER32!DispatchMessageWorker+0x249
34 00007ffe`ac87c5cc     : 00000000`00000000 00000000`00000000 00000000`00000000 00000002`00000030 : USER32!IsDialogMessageW+0x280
35 00007ffe`ac87c197     : 000000f5`9f94f688 00000000`00000000 00000000`00000000 00000000`00000000 : libui!processMessage+0x4c [D:\proj\Julia\libui-ng\windows\main.cpp @ 56] 
36 00007ffe`ac87c120     : 00000260`00000001 00007ff6`42110658 cccccccc`00000001 00000260`1929b8e0 : libui!uiMainStep+0x47 [D:\proj\Julia\libui-ng\windows\main.cpp @ 105] 
37 00007ff6`420f863f     : 00000260`13651580 00007ff6`42110658 00000260`1929b8e0 cdcdcdcd`cdcdcdcd : libui!uiMain+0x10 [D:\proj\Julia\libui-ng\windows\main.cpp @ 76] 
38 00007ff6`42102b59     : 00000c24`00000001 00000260`1361b3a0 00000000`00000000 00007ff6`421039ad : tester!main+0x5af [D:\proj\Julia\libui-ng\test\main.c @ 174] 
39 00007ff6`42102a7e     : 00007ff6`42106800 00007ff6`42106880 00000000`00000000 00000000`00000000 : tester!invoke_main+0x39 [d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 79] 
3a 00007ff6`4210293e     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : tester!__scrt_common_main_seh+0x12e [d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
3b 00007ff6`42102bce     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : tester!__scrt_common_main+0xe [d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 331] 
3c 00007fff`2e837034     : 000000f5`9fbda000 00000000`00000000 00000000`00000000 00000000`00000000 : tester!mainCRTStartup+0xe [d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp @ 17] 
3d 00007fff`2f722651     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : KERNEL32!BaseThreadInitThunk+0x14
3e 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21
```

</details>

**Comment by szanni** [comment]
> 

Not really surprised. The windows code has been broken for a long time! I am quite surprised it does not crash more often actually.
I am sure all windows code will keep crashing until [libui#416](https://github.com/andlabs/libui/issues/416)  is resolved (there seem to be numerous dupes). #20  should fix that. So if you could maybe test that one first, merge, and I am fairly certain all the other PRs will suddenly run without crashes on windows.

This is actually why this new tester is so important to me. I have uncovered numerous bugs on numerous platforms through the new tester. It covers code paths that were only rarely/never triggered by the tester in page16.

Does the crashing persist when merging #20 prior to this PR?

**Comment by inkydragon** [comment]
This pr + #17 + #20 works fine.

`destruc-table` wroks fine too. And `destruc-table` do crash on master branch.

**Comment by szanni** [comment]
> Is this same bug as `destruct-table` example [here](https://github.com/bcampbell/libui/commits/destruc-table)?

Yes. It is the double insertion bug (item counter get increased twice, hence an eventual out of bounds access to a non existing  table row).
`destruct-table` is the example code of [libui#416](https://github.com/andlabs/libui/issues/416), dupe:  [libui#524](https://github.com/andlabs/libui/issues/524) and even upstream [libui#369](https://github.com/andlabs/ui/issues/369). Windows will randomly keep crashing until this is fixed. Guaranteed.

**Comment by inkydragon** [comment]
I prefer to merge this test first. Merge order: #18, #17, #20

**Comment by szanni** [comment]
> I prefer to merge this test first. Merge order: #18, #17, #20

Merging the new test first would definitely highlight all the other bugs.

I do have a branch [table-fixes](https://github.com/szanni/libui-ng/tree/table-fixes) that I have been rebasing for my personal needs which consists of #16 #17 #19 #20 (in that order) if that would make things easier. That does not include #18 though.

**Comment by cody271** [comment]
@szanni which of these old uiTable PRs have been tested on all platforms?

**Comment by cody271** [comment]
> > I prefer to merge this test first. Merge order: #18, #17, #20
> 
> Merging the new test first would definitely highlight all the other bugs.
> 
> I do have a branch [table-fixes](https://github.com/szanni/libui-ng/tree/table-fixes) that I have been rebasing for my personal needs which consists of #16 #17 #19 #20 (in that order) if that would make things easier. That does not include #18 though.

This issue first, then the rest in ascending order ?

**Comment by szanni** [comment]
> @szanni which of these old uiTable PRs have been tested on all platforms?

I test all of my PRs on linux, mac, and wine (via mingw64 cross compile).

I sadly don't have enough spare space to install a 100GiB Windows VM with VS at this time. But the only issues that did arise in the past with this method were compile time errors (caught by CI), like the MS compiler not knowing `snprintf` and similar.

**Comment by cody271** [comment]
> I test all of my PRs on linux, mac, and wine (via mingw64 cross compile).
> 
👍

**Review by cody271 — APPROVED** [review]
Merging them all now, starting here with #18. LGTM.

**Pull request merged**
