### PR TITLE
windows: Fix time string length retrieval

### PR DESCRIPTION
**Pull request by kojix2**
Hello.

I was thinking about how I can contribute to the project easily and without any difficulty, and I came up with the idea of having ChatGPT review libui-ng.

According to ChatGPT, there is a mistake here.
It may indeed be so.

### CODE REVIEW

**Comment by szanni** [comment]
Looks like a legitimate bug to me.

The `GetLocaleInfoEx` docs sadly do not state returned string on error is actually `\0` terminated, so unsure if this would crash nonetheless on `datetime = strf(L"%s %s", date, time);`. But this patch definitely is an improvement and possibly all that is needed.

**Comment by cody271** [comment]
> Looks like a legitimate bug to me.

Confirmed bug, checks `ndate` for error result twice instead of `ntime`.

**Review by cody271 — APPROVED** [review]
LGTM

**Comment by rubyFeedback** [comment]
Interesting. I did not know ChatGPT can be used for finding bugs. Can this also be applied to e. g. a codebase in (pure) ruby?

**Pull request merged**
