### PR TITLE
annotate ui.h for doxygen

### PR DESCRIPTION
**Pull request by msink**
- use doxygen special commands for structuring
- missed documentatin copy-pasted from official Go bindings

### CODE REVIEW

**Comment by msink** [comment]
ready for review and hopefully merge

**Comment by cody271** [comment]
> ready for review and hopefully merge

Much improved here, I think we're close on this! Remaining issues I see:

This is missing the [enum](https://github.com/libui-ng/libui-ng/issues/3#issuecomment-1013216508) annotations, and needs to restrict visibility of the private APIs that are in the header.
I think doxygen is also still a bit confused as to which of our C struct type defs are meant to be "classes", and which are just plain struct types.

Since @msink, @inkydragon, and myself all have a conflicting branch for this..
I'm going to combine all of our changes into one single PR now, with above issues resolved.

**Comment by cody271** [comment]
Also- a few references to Go from the `andlabs/ui` godoc snuck in there .. 😛 

Need to keep everything plain C, will fix.

**Comment by szanni** [comment]
Any progress on this? I would love to expand on the documentation in some areas when this hits upstream.

And as a side note: I personally find the classic
```c
/**
 *
 */
```
infinitely easier to parse, as there is less visual clutter. But maybe that's just because that is the style most projects use that I have come in contact with.

**Comment by cody271** [comment]
Duplicate of #96

**Pull request closed without merging**
