### PR TITLE
[Linux+Windows] allow dialogs without a parent window.

### PR DESCRIPTION
**Pull request by msink**
Part of andlabs/libui#375
- untested
- macOS missed

### CODE REVIEW

**Comment by cody271** [comment]
Well since none of these melonDS PRs seem to have macOS implementations, they will all have to wait until I get to writing that.. Unless you're working on the macOS code?

**Comment by msink** [comment]
> you're working on the macOS code?
No, I do not have access to a Mac.

> they will all have to wait until I get to writing that
Of course.

**Comment by cody271** [comment]
[`uiDrawBitmap`](https://github.com/libui-ng/libui-ng/issues/30) will be first, unless someone points out another one that is a higher priority.

**Comment by cody271** [comment]
Replaced by #267.

**Pull request closed without merging**
