### PR TITLE
Add Ardillo PHP language binding

### PR DESCRIPTION
**Pull request by cdosoftei**

### CODE REVIEW

**Comment by cody271** [comment]
"Adrillo" or "Ardillo" ? 😛

**Comment by cdosoftei** [comment]
Most definitely Ardillo :smile: ... the virtues of peer reviews!

**Review by cody271 — COMMENTED** [review]
Need to force push the updated commit message as well.

**Comment by cdosoftei** [comment]
Best practice makes perfect :D

**Review by cody271 — APPROVED** [review]
LGTM

**Pull request merged**
